### ISSUE TITLE
Incompatible with mod "Follow me"

### ISSUE THREAD

**Issue by kjetilpaulsen** [schliesser/fs-noteleport#2]
Compatibility report. Using this mod together with Follow me/Followme made it impossible to initialize the follow me action. Remapping the keys for follow me did not fix the issue. I haven't seen any other posts about this, so unsure if it's just me. 

(Edit; main reason for raising the issue is awareness. I had to test by selecting/deselecting a few hundred mods.)

**Comment by MrTazzzik** [comment]
I confirm that I also have a No Teleport mod that makes the Follow me mod not work

**Comment by schliesser** [comment]
Thanks for the report. I'll check if I can do anything about the incompatibility. Otherwise I add a note to the description.

@noorac @MrTazzzik Can you confirm that it's this follow me mod?
https://www.farming-simulator.com/mod.php?mod_id=244513

**Comment by kjetilpaulsen** [comment]
@schliesser sorry it took so long to reply. Yes, it should be that mod, if I remember correctly(no longer have FS installed). Seems you have resolved the issue already though.
