### ISSUE TITLE
Bug after deactivating mod on saves (TAB for vehicle switch not working anymore)

### ISSUE THREAD

**Issue by ResidentIwen** [schliesser/fs-noteleport#3]
Hello, I recently added your no teleport mod to a serversave of mine, because I like the rpg/realism that it provides and wanted to try it. Unfortunately my friends also playing on the server didn't fully approve the hustle this mod comes with naturally, so I removed it again 2 days later. Somehow, after I removed it, teleport via map menu was available again, but the vehicle switch by pressing TAB didn't work anymore (tried out some other key mappings for it and they didn't work either). Luckily since it was only two days active I could restore the save with a backup, but if it would have been a longer time it could've been irreversable (at least I think). So it wasn't really a problem, but just wanted to let you know, that this might happen.
Best wishes :)

**Comment by schliesser** [comment]
Hey @ResidentIwen 

thank you very much for your nice bug report. I can't imagine how this mod can influence the savegame as it only overrides the base game functions during runtime. Would it be possible for you to share the broken savegame with me somehow? Maybe via discord -tinte-#7539 ?

Thanks

**Comment by schliesser** [comment]
No reaction for a long time -> closing the issue.
